### ISSUE TITLE
SE header fix: Always showing green cup when you have upvotes

### ISSUE THREAD

**Issue by eyalroz** [gingershaped/userscripts#1]
SE's chalice icon is green if you've reached some achievement; and has a green balloon with +N when you've acquired N reputation points. Those two are orthogonal, so you might have a grayed-out chalice with a green balloon. But... with the user script on, whenever the balloon is on, the chalice is green even when it should not be.

**Comment by gingershaped** [comment]
Oh, sorry. Forgot that was how it worked. I may not be able to fix this, but I'll give it a shot.
