### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by aminasisic** [gingershaped/userscripts#2]
This is the first time I'm trying to use a userscript. I'm getting the following error when trying to compile the script:

<img width="1439" alt="Screenshot 2023-05-31 at 12 58 33" src="https://github.com/GingerIndustries/userscripts/assets/67382365/cb867ae3-7ccd-4a0e-b11b-d8c23150e40c">

What can I do?

**Comment by gingershaped** [comment]
This is not a userscript, but a user _style_. It's designed to be used with extensions like Stylus, which you can find in the nearest extension store.

**Comment by aminasisic** [comment]
Fantastic, thank you for responding so quickly and solving the issue.
