### ISSUE TITLE
Color doesn't seem to be applying in SE Voting Fix

### ISSUE THREAD

**Issue by ssokolow** [gingershaped/userscripts#3]
`color: var(#babfc4) !important;` seems to be getting ignored/overridden in `.js-voting-container button.bar-pill.fc-black-700`.

![Screenshot 2023-06-01 at 08-19-36 Is it possible to write unit tests in Applesoft BASIC](https://github.com/GingerIndustries/userscripts/assets/46915/dd513c91-ce57-45f6-b927-2352d69dc840)

As a workaround, I added `opacity: .30;` to it:

![Screenshot 2023-06-01 at 08-20-51 Is it possible to write unit tests in Applesoft BASIC](https://github.com/GingerIndustries/userscripts/assets/46915/94e6d99c-63ac-4de7-b6bd-fbf2cbe12f8d)

(Yeah, I should probably have added `!important` but, given that it's my own tweak on a thing I had to copy-paste to get Stylus's Firefox style importer to kick in, it'll help me to remember to go check for updates manually if it breaks.)

**Comment by gingershaped** [comment]
I've implemented this fix. Not sure why it happens and not really willing to go find out. Frankly I'm tired of fixing SE's bad UI decisions for them.

**Comment by latere-a-latere** [comment]
`color: var(#babfc4) !important;` didn't work because it's invalid CSS. `#babfc4` is a raw hex value and not a CSS variable, so calling it with `var()` doesn't do anything.

My PR #4 corrects this issue properly. Instead of using opacity to fix the color, it now sets a variable and uses that instead.

**Comment by ssokolow** [comment]
\*facepalm* Just goes to show how badly I'd slept on June 1st that I didn't immediately see that.
